# Generated by Django 6.0.5 on 2026-05-09 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('roasting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuppingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cupping_date', models.DateTimeField(verbose_name='杯测日期')),
                ('cupper', models.CharField(blank=True, max_length=100, verbose_name='杯测师')),
                ('aroma', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='香气')),
                ('flavor', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='风味')),
                ('aftertaste', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='余韵')),
                ('acidity', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='酸度')),
                ('body', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='醇厚度')),
                ('balance', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='平衡感')),
                ('uniformity', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='一致性')),
                ('clean_cup', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='干净度')),
                ('sweetness', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='甜感')),
                ('overall', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='综合评价')),
                ('total_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='总分')),
                ('brew_method', models.CharField(blank=True, max_length=100, verbose_name='冲煮方式')),
                ('brew_ratio', models.CharField(blank=True, max_length=50, verbose_name='粉水比')),
                ('grind_size', models.CharField(blank=True, max_length=100, verbose_name='研磨度')),
                ('water_temp', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='水温(℃)')),
                ('brew_time', models.CharField(blank=True, max_length=50, verbose_name='冲煮时间')),
                ('flavor_notes', models.TextField(blank=True, verbose_name='风味描述')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('roast_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roasting.roastingprofile', verbose_name='烘焙批次')),
            ],
            options={
                'verbose_name': '杯测记录',
                'verbose_name_plural': '杯测记录',
                'ordering': ['-cupping_date'],
            },
        ),
    ]
