<?php

namespace Proxies\__CG__\App\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Lens extends \App\Entity\Lens implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Lens' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Lens' . "\0" . 'brand', '' . "\0" . 'App\\Entity\\Lens' . "\0" . 'model', '' . "\0" . 'App\\Entity\\Lens' . "\0" . 'mountType', '' . "\0" . 'App\\Entity\\Lens' . "\0" . 'focalLength', '' . "\0" . 'App\\Entity\\Lens' . "\0" . 'maxAperture', '' . "\0" . 'App\\Entity\\Lens' . "\0" . 'minAperture', '' . "\0" . 'App\\Entity\\Lens' . "\0" . 'productionYear', '' . "\0" . 'App\\Entity\\Lens' . "\0" . 'description', '' . "\0" . 'App\\Entity\\Lens' . "\0" . 'condition', '' . "\0" . 'App\\Entity\\Lens' . "\0" . 'purchasePrice', '' . "\0" . 'App\\Entity\\Lens' . "\0" . 'purchaseDate', '' . "\0" . 'App\\Entity\\Lens' . "\0" . 'serialNumber', '' . "\0" . 'App\\Entity\\Lens' . "\0" . 'hasAutoFocus', '' . "\0" . 'App\\Entity\\Lens' . "\0" . 'createdAt', '' . "\0" . 'App\\Entity\\Lens' . "\0" . 'updatedAt', '' . "\0" . 'App\\Entity\\Lens' . "\0" . 'samplePhotos', '' . "\0" . 'App\\Entity\\Lens' . "\0" . 'maintenanceRecords'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Lens' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Lens' . "\0" . 'brand', '' . "\0" . 'App\\Entity\\Lens' . "\0" . 'model', '' . "\0" . 'App\\Entity\\Lens' . "\0" . 'mountType', '' . "\0" . 'App\\Entity\\Lens' . "\0" . 'focalLength', '' . "\0" . 'App\\Entity\\Lens' . "\0" . 'maxAperture', '' . "\0" . 'App\\Entity\\Lens' . "\0" . 'minAperture', '' . "\0" . 'App\\Entity\\Lens' . "\0" . 'productionYear', '' . "\0" . 'App\\Entity\\Lens' . "\0" . 'description', '' . "\0" . 'App\\Entity\\Lens' . "\0" . 'condition', '' . "\0" . 'App\\Entity\\Lens' . "\0" . 'purchasePrice', '' . "\0" . 'App\\Entity\\Lens' . "\0" . 'purchaseDate', '' . "\0" . 'App\\Entity\\Lens' . "\0" . 'serialNumber', '' . "\0" . 'App\\Entity\\Lens' . "\0" . 'hasAutoFocus', '' . "\0" . 'App\\Entity\\Lens' . "\0" . 'createdAt', '' . "\0" . 'App\\Entity\\Lens' . "\0" . 'updatedAt', '' . "\0" . 'App\\Entity\\Lens' . "\0" . 'samplePhotos', '' . "\0" . 'App\\Entity\\Lens' . "\0" . 'maintenanceRecords'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Lens $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(?\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(?\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getBrand(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBrand', []);

        return parent::getBrand();
    }

    /**
     * {@inheritDoc}
     */
    public function setBrand(string $brand): \App\Entity\Lens
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBrand', [$brand]);

        return parent::setBrand($brand);
    }

    /**
     * {@inheritDoc}
     */
    public function getModel(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getModel', []);

        return parent::getModel();
    }

    /**
     * {@inheritDoc}
     */
    public function setModel(string $model): \App\Entity\Lens
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setModel', [$model]);

        return parent::setModel($model);
    }

    /**
     * {@inheritDoc}
     */
    public function getMountType(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMountType', []);

        return parent::getMountType();
    }

    /**
     * {@inheritDoc}
     */
    public function setMountType(string $mountType): \App\Entity\Lens
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMountType', [$mountType]);

        return parent::setMountType($mountType);
    }

    /**
     * {@inheritDoc}
     */
    public function getFocalLength(): ?float
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFocalLength', []);

        return parent::getFocalLength();
    }

    /**
     * {@inheritDoc}
     */
    public function setFocalLength(float $focalLength): \App\Entity\Lens
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFocalLength', [$focalLength]);

        return parent::setFocalLength($focalLength);
    }

    /**
     * {@inheritDoc}
     */
    public function getMaxAperture(): ?float
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMaxAperture', []);

        return parent::getMaxAperture();
    }

    /**
     * {@inheritDoc}
     */
    public function setMaxAperture(?float $maxAperture): \App\Entity\Lens
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMaxAperture', [$maxAperture]);

        return parent::setMaxAperture($maxAperture);
    }

    /**
     * {@inheritDoc}
     */
    public function getMinAperture(): ?float
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMinAperture', []);

        return parent::getMinAperture();
    }

    /**
     * {@inheritDoc}
     */
    public function setMinAperture(?float $minAperture): \App\Entity\Lens
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMinAperture', [$minAperture]);

        return parent::setMinAperture($minAperture);
    }

    /**
     * {@inheritDoc}
     */
    public function getProductionYear(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProductionYear', []);

        return parent::getProductionYear();
    }

    /**
     * {@inheritDoc}
     */
    public function setProductionYear(?int $productionYear): \App\Entity\Lens
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProductionYear', [$productionYear]);

        return parent::setProductionYear($productionYear);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', []);

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription(?string $description): \App\Entity\Lens
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', [$description]);

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getCondition(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCondition', []);

        return parent::getCondition();
    }

    /**
     * {@inheritDoc}
     */
    public function setCondition(?string $condition): \App\Entity\Lens
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCondition', [$condition]);

        return parent::setCondition($condition);
    }

    /**
     * {@inheritDoc}
     */
    public function getPurchasePrice(): ?float
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPurchasePrice', []);

        return parent::getPurchasePrice();
    }

    /**
     * {@inheritDoc}
     */
    public function setPurchasePrice(?float $purchasePrice): \App\Entity\Lens
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPurchasePrice', [$purchasePrice]);

        return parent::setPurchasePrice($purchasePrice);
    }

    /**
     * {@inheritDoc}
     */
    public function getPurchaseDate(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPurchaseDate', []);

        return parent::getPurchaseDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setPurchaseDate(\DateTimeInterface $purchaseDate): \App\Entity\Lens
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPurchaseDate', [$purchaseDate]);

        return parent::setPurchaseDate($purchaseDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getSerialNumber(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSerialNumber', []);

        return parent::getSerialNumber();
    }

    /**
     * {@inheritDoc}
     */
    public function setSerialNumber(?string $serialNumber): \App\Entity\Lens
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSerialNumber', [$serialNumber]);

        return parent::setSerialNumber($serialNumber);
    }

    /**
     * {@inheritDoc}
     */
    public function isHasAutoFocus(): bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isHasAutoFocus', []);

        return parent::isHasAutoFocus();
    }

    /**
     * {@inheritDoc}
     */
    public function setHasAutoFocus(bool $hasAutoFocus): \App\Entity\Lens
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHasAutoFocus', [$hasAutoFocus]);

        return parent::setHasAutoFocus($hasAutoFocus);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedAt(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedAt', []);

        return parent::getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedAt(\DateTimeInterface $createdAt): \App\Entity\Lens
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedAt', [$createdAt]);

        return parent::setCreatedAt($createdAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdatedAt(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedAt', []);

        return parent::getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdatedAt(\DateTimeInterface $updatedAt): \App\Entity\Lens
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedAt', [$updatedAt]);

        return parent::setUpdatedAt($updatedAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getSamplePhotos(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSamplePhotos', []);

        return parent::getSamplePhotos();
    }

    /**
     * {@inheritDoc}
     */
    public function addSamplePhoto(\App\Entity\SamplePhoto $samplePhoto): \App\Entity\Lens
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addSamplePhoto', [$samplePhoto]);

        return parent::addSamplePhoto($samplePhoto);
    }

    /**
     * {@inheritDoc}
     */
    public function removeSamplePhoto(\App\Entity\SamplePhoto $samplePhoto): \App\Entity\Lens
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeSamplePhoto', [$samplePhoto]);

        return parent::removeSamplePhoto($samplePhoto);
    }

    /**
     * {@inheritDoc}
     */
    public function getMaintenanceRecords(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMaintenanceRecords', []);

        return parent::getMaintenanceRecords();
    }

    /**
     * {@inheritDoc}
     */
    public function addMaintenanceRecord(\App\Entity\MaintenanceRecord $maintenanceRecord): \App\Entity\Lens
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addMaintenanceRecord', [$maintenanceRecord]);

        return parent::addMaintenanceRecord($maintenanceRecord);
    }

    /**
     * {@inheritDoc}
     */
    public function removeMaintenanceRecord(\App\Entity\MaintenanceRecord $maintenanceRecord): \App\Entity\Lens
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeMaintenanceRecord', [$maintenanceRecord]);

        return parent::removeMaintenanceRecord($maintenanceRecord);
    }

}
