# Generated by Django 6.0.5 on 2026-05-09 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('beans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoastingProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(max_length=50, unique=True, verbose_name='批次号')),
                ('input_weight', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='入豆重量(g)')),
                ('output_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='出豆重量(g)')),
                ('roast_date', models.DateTimeField(verbose_name='烘焙日期')),
                ('roaster_model', models.CharField(blank=True, max_length=100, verbose_name='烘焙机型号')),
                ('roast_level', models.CharField(blank=True, max_length=50, verbose_name='烘焙度')),
                ('charge_temp', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='入豆温度(℃)')),
                ('dry_end_time', models.IntegerField(blank=True, null=True, verbose_name='脱水结束时间(秒)')),
                ('dry_end_temp', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='脱水结束温度(℃)')),
                ('fc_start_time', models.IntegerField(blank=True, null=True, verbose_name='一爆开始时间(秒)')),
                ('fc_start_temp', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='一爆开始温度(℃)')),
                ('fc_end_time', models.IntegerField(blank=True, null=True, verbose_name='一爆结束时间(秒)')),
                ('fc_end_temp', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='一爆结束温度(℃)')),
                ('sc_start_time', models.IntegerField(blank=True, null=True, verbose_name='二爆开始时间(秒)')),
                ('sc_start_temp', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='二爆开始温度(℃)')),
                ('drop_time', models.IntegerField(verbose_name='下豆时间(秒)')),
                ('drop_temp', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='下豆温度(℃)')),
                ('notes', models.TextField(blank=True, verbose_name='烘焙笔记')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('green_bean', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beans.coffeebean', verbose_name='生豆')),
            ],
            options={
                'verbose_name': '烘焙记录',
                'verbose_name_plural': '烘焙记录',
                'ordering': ['-roast_date'],
            },
        ),
        migrations.CreateModel(
            name='TemperaturePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_seconds', models.IntegerField(verbose_name='时间(秒)')),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='温度(℃)')),
                ('roast_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temperature_points', to='roasting.roastingprofile', verbose_name='烘焙曲线')),
            ],
            options={
                'verbose_name': '温度点',
                'verbose_name_plural': '温度点',
                'ordering': ['time_seconds'],
            },
        ),
    ]
