# Generated by Django 6.0.5 on 2026-05-09 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoffeeBean',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='生豆名称')),
                ('origin_country', models.CharField(max_length=100, verbose_name='原产国')),
                ('region', models.CharField(blank=True, max_length=100, verbose_name='产区')),
                ('farm', models.CharField(blank=True, max_length=200, verbose_name='庄园')),
                ('altitude', models.CharField(blank=True, max_length=100, verbose_name='海拔')),
                ('variety', models.CharField(blank=True, max_length=100, verbose_name='品种')),
                ('process_method', models.CharField(blank=True, max_length=100, verbose_name='处理法')),
                ('cupping_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='杯测分数')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='采购日期')),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='单价(元/kg)')),
                ('total_weight', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='总重量(kg)')),
                ('remaining_weight', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='剩余重量(kg)')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='suppliers.supplier', verbose_name='供应商')),
            ],
            options={
                'verbose_name': '生豆库存',
                'verbose_name_plural': '生豆库存',
                'ordering': ['-created_at'],
            },
        ),
    ]
