<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVtvFsUn\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVtvFsUn/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVtvFsUn.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVtvFsUn\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerVtvFsUn\App_KernelDevDebugContainer([
    'container.build_hash' => 'VtvFsUn',
    'container.build_id' => 'adf9e728',
    'container.build_time' => 1778411020,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVtvFsUn');
