# Generated by Django 6.0.5 on 2026-05-09 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Roaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='烘焙机名称')),
                ('model', models.CharField(blank=True, max_length=100, verbose_name='型号')),
                ('brand', models.CharField(blank=True, max_length=100, verbose_name='品牌')),
                ('capacity', models.CharField(blank=True, max_length=100, verbose_name='容量')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='购买日期')),
                ('serial_number', models.CharField(blank=True, max_length=200, verbose_name='序列号')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '烘焙机',
                'verbose_name_plural': '烘焙机',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_type', models.CharField(choices=[('cleaning', '清洁'), ('calibration', '校准'), ('repair', '维修'), ('inspection', '检查'), ('replacement', '零件更换'), ('other', '其他')], max_length=50, verbose_name='维护类型')),
                ('maintenance_date', models.DateTimeField(verbose_name='维护日期')),
                ('technician', models.CharField(blank=True, max_length=100, verbose_name='技术员')),
                ('description', models.TextField(verbose_name='维护描述')),
                ('parts_replaced', models.TextField(blank=True, verbose_name='更换零件')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='费用(元)')),
                ('next_maintenance_date', models.DateField(blank=True, null=True, verbose_name='下次维护日期')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('roaster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maintenance.roaster', verbose_name='烘焙机')),
            ],
            options={
                'verbose_name': '维护记录',
                'verbose_name_plural': '维护记录',
                'ordering': ['-maintenance_date'],
            },
        ),
    ]
